### ISSUE TITLE
从Docker容器中访问宿主机网络

### ISSUE THREAD

**Issue by RandolphChin** [RandolphChin/RandolphChin.github.io#242]
来源于[Frank](https://nyan.im/posts/3981.html)的《从Docker容器中访问宿主机网络》
在使用Docker部署应用时，Docker推荐的方式是将应用及其所依赖的服务（MySQL，Redis等）均使用Docker部署，并通过link或自定义网络相连接。但是，当应用所依赖的服务被安装在宿主机上时，我们需要让容器中的应用能够访问到部署在宿主机上的服务。
Docker提供的常见网络类型
>1. bridge
>2. host

#### Bridge
Bridge是Docker默认使用的网络类型。如图，网络中的所有容器可以通过IP互相访问。Bridge网络通过网络接口docker0 与主机桥接，可以在主机上通过ifconfig docker0查看到该网络接口的信息
```
-bash-4.2# ifconfig docker0
docker0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        inet6 fe80::42:64ff:fe2a:2c74  prefixlen 64  scopeid 0x20<link>
        ether 02:42:64:2a:2c:74  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 690 (690.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```
![image](https://user-images.githubusercontent.com/19374409/72676213-b05ddb80-3ac9-11ea-8cf8-9a3da29c378b.png)

在默认的bridge模式下，docker0网络的默认网关即是宿主机。在Linux下，docker0网络通常会分配一个172.17.0.0/16的网段，其网关通常为172.17.0.1；macOS下的网段则为192.168.65.0/24，网关为192.168.65.1。在容器中使用该IP地址即可访问宿主机上的各种服务。

需要注意的是，这种情况下，经由docker0网桥而来的流量不经过宿主机的本地回环，因此需要将宿主机上的应用（MySQL，Redis等）配置为监听0.0.0.0。
优点
>避免了host网络的缺点，可以用于Window版本的docker

缺点
>此IP并不一定完全固定，可能会因系统及配置而发生变化。
>容器经由docker0网桥无法访问到监听地址是127.0.0.1的应用。需要将MySQL等配置为监听0.0.0.0。

#### 使用Host模式(Only Linux)
Host模式下，容器的网络接口不与宿主机网络隔离。在容器中监听相应端口的应用能够直接被从宿主机访问。host网络仅支持Linux
在compose文件中指定network_mode: "host"，for example
```
version: '2'
services:
  Eureka:
    image: 192.168.0.110:5000/lct-eureka-server
    ports:
      - "9091:9091"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime
      - /var/log/lct-eureka-server:/log
    network_mode: "host"
```
优点
>最简单粗暴的解决方案，方便快捷。

缺点
>host网络没有与宿主机网络隔离，可能引发安全隐患或端口冲突。
仅适用于Linux
