### ISSUE TITLE
gogs私有仓库搭建

### ISSUE THREAD

**Issue by RandolphChin** [RandolphChin/RandolphChin.github.io#256]
### DockerFile方式创建
分别创建 mysql容器和gogs容器，gogs容器 link到 mysql容器
1. 创建mysql容器
```
docker run -d -p 13306:3306 --name gogs-mysql -e MYSQL_ROOT_PASSWORD="root" -v /Users/wumingyang/gogsData:/var/lib/mysql   mysql:5.7.30
```
2. 创建数据库gogs 
```
CREATE DATABASE `gogs` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
```
3. 创建gogs服务
```
docker run -d -p 11022:22 -p 11080:3000 --name gogsweb -v /Users/wumingyang/gogsWeb:/data --link gogs-mysql:gogs-mysql gogs/gogs
```

#### 创建docker
宿主机目录映射容器目录  /var/gogs -> /data
```
# Pull image from Docker Hub.
$ docker pull gogs/gogs

# Create local directory for volume.
$ mkdir -p /var/gogs

# Use `docker run` for the first time.
$ docker run --name=gogs -p 10022:22 -p 10080:3000 -v /var/gogs:/data gogs/gogs

# Use `docker start` if you have stopped it.
$ docker start gogs
```
目录结构
```
/var/gogs
|-- git
|   |-- gogs-repositories
|-- ssh
|   |-- # ssh public/private keys for Gogs
|-- gogs
    |-- conf
    |-- data
    |-- log
```
使用 docker-compose.yml
```
version: '2'

services:
  mysql:
    image: mysql:5.7
    ports:
      - 33060:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gogs
    volumes:
      - /var/mydata:/var/lib/mysql
  gogs:
    image: gogs/gogs:latest
    ports:
      - 22:22
      - 11080:3000
    volumes:
      - /data/gogs:/data
    links:
      - mysql
    depends_on:
      - mysql

```
### docker-compose.yml方式创建
```
version: '2'

services:
  mysql:
    image: mysql:5.7.30
    ports:
      - '13306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gogs
    volumes:
      - /Users/wumingyang/mydata:/var/lib/mysql
    container_name: gogs-mysql
  gogs:
    image: gogs/gogs:latest
    ports:
      - '11081:22'
      - '11080:3000'
    volumes:
      - /Users/wumingyang/gogsData:/data
    container_name: gogsweb
    links:
      - mysql
    depends_on:
      - mysql
```
需要注意：
>ports参数的映射需要加上单引号，否则会出现容器创建成功，但是无法进入到mysql容器中创建数据库

```
version: '3.8'

services:
  mysql:
    image: mysql:8.4.5
    environment:
      MYSQL_ROOT_PASSWORD: gogs
      MYSQL_DATABASE: gogs
      MYSQL_USER: gogs
      MYSQL_PASSWORD: gogs
    volumes:
      - ./mysql-data:/var/lib/mysql

  gogs:
    image: gogs/gogs:latest
    depends_on:
      - mysql
    volumes:
      - ./gogs-data:/data
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:10022:22"
```
注意：MySQL 不需要映射端口，因为只给 gogs 容器内部访问即可。
```
version: '3.8'

services:
  mysql:
    image: mysql:8.4.5
    environment:
      MYSQL_ROOT_PASSWORD: gogs
      MYSQL_DATABASE: gogs
      MYSQL_USER: gogs
      MYSQL_PASSWORD: gogs
    volumes:
      - ./mysql-data:/var/lib/mysql

  gogs:
    image: gogs/gogs:latest
    depends_on:
      - mysql
    volumes:
      - ./gogs-data:/data
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:10022:22"
```
#### nginx配置
```
upstream gogs {
   server 127.0.0.1:11080 fail_timeout=0;
}
server {
    listen	443 ssl http2;
    server_name git.qh.com;

    ssl on;
    ssl_certificate      /etc/nginx/ssl/fullchain.cer;
    ssl_certificate_key  /etc/nginx/ssl/kikakika.key;
    ssl_session_cache    shared:SSL:1m;
    ssl_session_timeout  5m;
    ssl_prefer_server_ciphers  on;

    location / {
        proxy_pass http://gogs;
    }
}
server {
    listen  80;
    server_name git.qh.com;
    
    return	301 https://$server_name$request_uri;
}
```
