### ISSUE TITLE
minIO对象存储系统整合springboot

### ISSUE THREAD

**Issue by RandolphChin** [RandolphChin/RandolphChin.github.io#266]
### Docker 启动minIO
单机部署
```
docker run -p 9000:9000 \
  --name minio1 \
  -v /mnt/data:/data \
  -e "MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE" \
  -e "MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY" \
  minio/minio server /data
```
最新版本minio 需要指定 console-address 端口
```
docker run -p 9090:9090 -p 9000:9000  \
  --name minio -e MINIO_ACCESS_KEY=bfrj -e MINIO_SECRET_KEY=bfrj8526660  \
  --restart=always -v /home/dockerFile/minio/data:/data  \
   -v /home/dockerFile/minio/config:/root/.minio  \
    minio/minio:latest server --console-address ":9090" --address ":9000" /data
```
分布式部署
docker-compose.yaml
```
version: '3.7'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2021-11-09T03-21-45Z
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: minio
    MINIO_ROOT_PASSWORD: minio123
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - D:/tool/dockerFile/example-minio/data1-1:/data1
      - D:/tool/dockerFile/example-minio/data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - D:/tool/dockerFile/example-minio/data2-1:/data1
      - D:/tool/dockerFile/example-minio/data2-2:/data2

  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - D:/tool/dockerFile/example-minio/data3-1:/data1
      - D:/tool/dockerFile/example-minio/data3-2:/data2

  minio4:
    <<: *minio-common
    hostname: minio4
    volumes:
      - D:/tool/dockerFile/example-minio/data4-1:/data1
      - D:/tool/dockerFile/example-minio/data4-2:/data2

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
#volumes:
#  data1-1:
#  data1-2:
#  data2-1:
#  data2-2:
#  data3-1:
#  data3-2:
#  data4-1:
#  data4-2:
```
nginx.conf
```
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  4096;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;
    sendfile        on;
    keepalive_timeout  65;

    # include /etc/nginx/conf.d/*.conf;

    upstream minio {
        server minio1:9000;
        server minio2:9000;
        server minio3:9000;
        server minio4:9000;
    }

    upstream console {
        ip_hash;
        server minio1:9001;
        server minio2:9001;
        server minio3:9001;
        server minio4:9001;
    }

    server {
        listen       9000;
        listen  [::]:9000;
        server_name  localhost;

        # To allow special characters in headers
        ignore_invalid_headers off;
        # Allow any size file to be uploaded.
        # Set to a value such as 1000m; to restrict file size to a specific value
        client_max_body_size 0;
        # To disable buffering
        proxy_buffering off;

        location / {
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_connect_timeout 300;
            # Default is HTTP/1, keepalive is only enabled in HTTP/1.1
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            chunked_transfer_encoding off;

            proxy_pass http://minio;
        }
    }

    server {
        listen       9001;
        listen  [::]:9001;
        server_name  localhost;

        # To allow special characters in headers
        ignore_invalid_headers off;
        # Allow any size file to be uploaded.
        # Set to a value such as 1000m; to restrict file size to a specific value
        client_max_body_size 0;
        # To disable buffering
        proxy_buffering off;

        location / {
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-NginX-Proxy true;

            # This is necessary to pass the correct IP to be hashed
            real_ip_header X-Real-IP;

            proxy_connect_timeout 300;
            
            # To support websocket
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            
            chunked_transfer_encoding off;

            proxy_pass http://console;
        }
    }
}

```
#### dependency
```
<dependency>
    <groupId>io.minio</groupId>
    <artifactId>minio</artifactId>
    <version>7.1.2</version>
</dependency>
```
#### yaml setting
```
min:
  io:
    endpoint: http://127.0.0.1:9000
    accessKey: minioadmin
    secretKey: minioadmin
    bucketName: test2
```
#### start minIO
>minIo.exe server D:/datas

#### 相关类
Controller
```Java
@RestController
@RequestMapping("/api/minio")
public class MinIoController {
    @Autowired
    MinIoProperties minIoProperties;
    @Autowired
    Minio minio;

    @PostMapping(value = "/upload")
    public String upload(@RequestParam("file") MultipartFile file) throws Exception {
        String fileUrl = minio.upload(minIoProperties.getBucketName(),file.getOriginalFilename(), file);
        return "文件下载地址：" + fileUrl;
    }
}
```
MinIoProperties.java
```Java
@Configuration
@Data
public class MinIoProperties {
    @Value("${min.io.endpoint}")
    private String endpoint;
    @Value("${min.io.accessKey}")
    private String accessKey;
    @Value("${min.io.secretKey}")
    private String secretKey;
    @Value("${min.io.bucketName}")
    private String bucketName;
}
```
Minio.java
```Java
import javax.annotation.PostConstruct;
@Component
public class Minio {
    @Autowired
    private MinIoProperties minIoProperties;

    private MinioClient client;

    /**
     * 桶占位符
     */
    private static final String BUCKET_PARAM = "${bucket}";
    /**
     * bucket权限-只读
     */
    private static final String READ_ONLY = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"AWS\":[\"*\"]},\"Action\":[\"s3:GetBucketLocation\",\"s3:ListBucket\"],\"Resource\":[\"arn:aws:s3:::" + BUCKET_PARAM + "\"]},{\"Effect\":\"Allow\",\"Principal\":{\"AWS\":[\"*\"]},\"Action\":[\"s3:GetObject\"],\"Resource\":[\"arn:aws:s3:::" + BUCKET_PARAM + "/*\"]}]}";
    /**
     * bucket权限-只读
     */
    private static final String WRITE_ONLY = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"AWS\":[\"*\"]},\"Action\":[\"s3:GetBucketLocation\",\"s3:ListBucketMultipartUploads\"],\"Resource\":[\"arn:aws:s3:::" + BUCKET_PARAM + "\"]},{\"Effect\":\"Allow\",\"Principal\":{\"AWS\":[\"*\"]},\"Action\":[\"s3:AbortMultipartUpload\",\"s3:DeleteObject\",\"s3:ListMultipartUploadParts\",\"s3:PutObject\"],\"Resource\":[\"arn:aws:s3:::" + BUCKET_PARAM + "/*\"]}]}";
    /**
     * bucket权限-读写
     */
    private static final String READ_WRITE = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"AWS\":[\"*\"]},\"Action\":[\"s3:GetBucketLocation\",\"s3:ListBucket\",\"s3:ListBucketMultipartUploads\"],\"Resource\":[\"arn:aws:s3:::" + BUCKET_PARAM + "\"]},{\"Effect\":\"Allow\",\"Principal\":{\"AWS\":[\"*\"]},\"Action\":[\"s3:DeleteObject\",\"s3:GetObject\",\"s3:ListMultipartUploadParts\",\"s3:PutObject\",\"s3:AbortMultipartUpload\"],\"Resource\":[\"arn:aws:s3:::" + BUCKET_PARAM + "/*\"]}]}";

    /**
     * 初始化minio配置
     *
     * @param :
     * @return: void
     * @date : 2020/8/16 20:56
     */
    @PostConstruct
    public void init() {
        try {
            client = MinioClient.builder().endpoint(minIoProperties.getEndpoint()).credentials(minIoProperties.getAccessKey(), minIoProperties.getSecretKey()).build();
            makeBucket(minIoProperties.getBucketName());
            setBucketPolicy(minIoProperties.getBucketName(), "read-write");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * 文件url前半段
     *    示例  http://127.0.0.1:9000/test/Snipaste_2020-12-10_12-53-31.png
     * @param bucket 桶
     * @return 前半段
     */
    private String getObjectPrefixUrl(String bucket) {
        return String.format("%s/%s/", minIoProperties.getEndpoint(), bucket);
    }

    /**
     * 创建桶
     *
     * @param bucket 桶
     */
    public void makeBucket(String bucket) throws Exception {
        // 判断桶是否存在
        boolean isExist = client.bucketExists(BucketExistsArgs.builder().bucket(bucket).build());
        if (!isExist) {
            // 新建桶
            client.makeBucket(MakeBucketArgs.builder().bucket(bucket).build());
        }
    }

    /**
     * 更新桶权限策略
     *
     * @param bucket 桶
     * @param policy 权限
     */
    public void setBucketPolicy(String bucket, String policy) throws Exception {
        switch (policy) {
            case "read-only":
                client.setBucketPolicy(SetBucketPolicyArgs.builder().bucket(bucket).config(READ_ONLY.replace(BUCKET_PARAM, bucket)).build());
                break;
            case "write-only":
                client.setBucketPolicy(SetBucketPolicyArgs.builder().bucket(bucket).config(WRITE_ONLY.replace(BUCKET_PARAM, bucket)).build());
                break;
            case "read-write":
                client.setBucketPolicy(SetBucketPolicyArgs.builder().bucket(bucket).config(READ_WRITE.replace(BUCKET_PARAM, bucket)).build());
                break;
            case "none":
            default:
                break;
        }
    }

    /**
     * 上传本地文件
     *
     * @param bucket    桶
     * @param objectKey 文件key
     * @param filePath  文件路径
     * @return 文件url
     */
    public String uploadFile(String bucket, String objectKey, String filePath) throws Exception {
        client.uploadObject(UploadObjectArgs.builder().bucket(bucket).object(objectKey).filename(filePath).contentType("image/png").build());
        return getObjectPrefixUrl(bucket) + objectKey;
    }

    /**
     * 流式上传文件
     *
     * @param bucket      桶
     * @param objectKey   文件key  如果有分隔符号则会创建文件夹如 "demo/123.png";
     * @param file 文件输入流
     * @return 文件url
     */
    public String upload(String bucket, String objectKey, MultipartFile file) throws Exception {
        InputStream inputStream = file.getInputStream();
        client.putObject(PutObjectArgs.builder().bucket(bucket).object(objectKey).stream(inputStream, inputStream.available(), -1).contentType("image/png").build());
        inputStream.close();
        return getObjectPrefixUrl(bucket) + objectKey;
    }

    /**
     * 下载文件
     *
     * @param bucket    桶
     * @param objectKey 文件key
     * @return 文件流
     */
    public InputStream download(String bucket, String objectKey) throws Exception {
        return client.getObject(GetObjectArgs.builder().bucket(bucket).object(objectKey).build());
    }

    /**
     * 文件复制
     *
     * @param sourceBucket    源桶
     * @param sourceObjectKey 源文件key
     * @param bucket          桶
     * @param objectKey       文件key
     * @return 新文件url
     */
    public String copyFile(String sourceBucket, String sourceObjectKey, String bucket, String objectKey) throws Exception {
        CopySource source = CopySource.builder().bucket(sourceBucket).object(sourceObjectKey).build();
        client.copyObject(CopyObjectArgs.builder().bucket(bucket).object(objectKey).source(source).build());
        return getObjectPrefixUrl(bucket) + objectKey;
    }

    /**
     * 删除文件
     *
     * @param bucket    桶
     * @param objectKey 文件key
     */
    public void deleteFile(String bucket, String objectKey) throws Exception {
        client.removeObject(RemoveObjectArgs.builder().bucket(bucket).object(objectKey).build());
    }

    /**
     * 获取文件签名url
     *
     * @param bucket    桶
     * @param objectKey 文件key
     * @param expires   签名有效时间  单位秒
     * @return 文件签名地址
     */
    public String getSignedUrl(String bucket, String objectKey, int expires) throws Exception {
        return client.getPresignedObjectUrl(GetPresignedObjectUrlArgs.builder().method(Method.GET).bucket(bucket).object(objectKey).expiry(expires).build());
    }
```

获取预览地址
>minioClient.presignedGetObject(bucketName, fileName);
返回内容如下
```
http://127.0.0.1:9000/test2/Snipaste_2020-12-09_17-54-31.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minioadmin%2F20201209%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20201209T095857Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=7d59d7cb4f389311beb9530eb05a48ecd91cd99fc458156c6adeabcf290657ed
```

前端页面
```
<el-upload
        class="upload"
        :action="uploadAction"
        :headers="headers"
        list-type="picture"
        :show-file-list="false"
      >
        <el-button class="filter-item" icon="el-icon-upload2" type="success" plain>
          {{ $t('table.import') }}
        </el-button>
      </el-upload>

// 片断
data() {
    return {
      uploadAction: `${process.env.VUE_APP_BASE_API}system/api/minio/upload`,
      headers: {
        Authorization: `bearer ${getToken()}`
      }
    }
```
### mc 基本命令
```
docker run -it --entrypoint=/bin/sh minio/mc

添加MinIO存储服务
mc config host add minio http://172.17.0.1:9000 minioadmin minioadmin

显示MinIO服务器信息
mc admin info minio

显示MinIO服务器的控制台日志
mc admin console minio

get the current configuration for notify_amqp
>mc admin config get minio/ notify_amqp

rabbitmqctl set_permissions -p / mqtt-test '.' '.' '.*'


$ mc admin config set minio/ notify_amqp:1 exchange="bucketevents" exchange_type="fanout" mandatory="false" no_wait="false"  url="amqp://mqtt-test:mqtt-test@172.17.0.1:5672" auto_deleted="false" delivery_mode="0" durable="false" internal="false" routing_key="bucketlogs"

```
#### 1st 安装 mc
>docker run -it --entrypoint=/bin/sh minio/mc
#### 2nd mc 连接服务端
```
#方法1
mc config host add minio_188 http://10.191.73.188:9000 minioadmin minioadmin
mc config host add minio_28 http://10.191.73.28:9000 minioadmin minioadmin

#方法2
mc alias set minio_wuhan http:// 10.191.73.188:9000 minioadmin minioadmin
mc alias set minio_shenzhen http:// 10.191.73.28:9000 minioadmin minioadmin

```
#### 3rd 查看服务端信息
>mc admin info minio_128

#### 4th 实时同步服务端信息
  minio_188   同步至 minio_28
>mc mirror --remove --overwrite --watch  minio_188   minio_28

需要注意，第一次转换完数据后，目录bucket所有的 Policy Access　都是私有的，需要变更为 公有的
｀｀｀
# 列表minio中所有目录
mc ls minio_119/

# 设置 目录 Policy Access 权限
mc anonymous set public minio_119/111.doc
｀｀｀
# 只迁移某个桶内的文件
mc --debug mirror --overwrite --remove minio_31/cover-setting-template minio_185/cover-setting-template

需要注意 --debug是调试模式，目标minio服务端的桶cover-setting-template必须先手动创建
