### ISSUE TITLE
spring-cloud-starter-gateway转发websocket

### ISSUE THREAD

**Issue by RandolphChin** [RandolphChin/RandolphChin.github.io#267]
#### websocket
1. 是一种基于TCP连接的全双工(full-duplex)通讯协议，是一个应用层协议
2. 客户端和服务器都可以向对方主动发送和接收数据，浏览器和服务器只需要完成一次握手，两者之间就直接可以创建持久性的连接
3. 在JS中创建WebSocket后，会有一个HTTP请求从浏览器发向服务器。在取得服务器响应后，建立的连接会使用HTTP升级将HTTP协议转换为WebSocket协议。
#### Stomp
1. STOMP(Simple Text-Orientated Messaging Protocol)，面向消息的简单文本协议
2. 定义了两种传输信息类型：文本信息和二进制信息
3. 是基于帧的协议，客户端和服务器使用STOMP帧流通讯
#### 要解决的问题
第一次建立WebSocket的连接的协议是HTTP或HTTPS协议，建立成功之后，url使用的是ws://或wss://
这里解决的问题是 spring-cloud-starter-gateway 如何转发 websocket

参考[嗷嗷待哺](https://www.bl-blog.com/a/9/27)
前台端分离websocket项目源于[BenHampton](https://github.com/BenHampton/websocket-chat-applicaiton.git)
#### 主要 dependency
```
<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-gateway</artifactId>
            <version>2.2.0.RELEASE</version>
 </dependency>
```
#### spring-cloud-starter-gateway 配置(Nacos)
spring cloud项目，多模块，websocket 位于 FEBS-Server-System模块
```
server:
  port: 8301
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: FEBS-Auth-Social
          uri: lb://FEBS-Auth
          predicates:
            - Path=/auth/social/**
          filters:
            - name: Hystrix
              args:
                name: socialfallback
                fallbackUri: forward:/fallback/FEBS-Auth
        - id: FEBS-Auth
          uri: lb://FEBS-Auth
          predicates:
            - Path=/auth/**
          filters:
            - name: Hystrix
              args:
                name: authfallback
                fallbackUri: forward:/fallback/FEBS-Auth            
        - id: FEBS-Server-System
          uri: lb://FEBS-Server-System
          predicates:
            - Path=/system/**
          filters:
            - name: Hystrix
              args:
                name: systemfallback
                fallbackUri: forward:/fallback/FEBS-Server-System
        - id: FEBS-Server-System-ws
          uri: lb:ws://FEBS-Server-System
          predicates:
            - Path=/system/**             
        - id: FEBS-Server-Generator
          uri: lb://FEBS-Server-Generator
          predicates:
            - Path=/generator/**
          filters:
            - name: Hystrix
              args:
                name: generatorfallback
                fallbackUri: forward:/fallback/FEBS-Server-Generator
        - id: FEBS-Server-Job
          uri: lb://FEBS-Server-Job
          predicates:
            - Path=/job/**
          filters:
            - name: Hystrix
              args:
                name: jobfallback
                fallbackUri: forward:/fallback/FEBS-Server-Job
        - id: FEBS-Server-test
          uri: lb://FEBS-Server-Test
          predicates:
            - Path=/test/**
          filters:
            - name: Hystrix
              args:
                name: testfallback
                fallbackUri: forward:/fallback/FEBS-Server-Test    
      loadbalancer:
        use404: true
      default-filters:
        - StripPrefix=1
        - FebsDocGatewayHeaderFilter
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration,org.springframework.boot.autoconfigure.data.mongo.MongoReactiveRepositoriesAutoConfiguration,org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
    
# 网关增强配置
  # data:
  #   mongodb:
  #     host: ${mongo.url}
  #     port: 27017
  #     database: febs_cloud_route

  redis:
    database: 3
    host: ${redis.url}
    port: 6379
    lettuce:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000

# 网关增强配置
febs:
  gateway:
    enhance: false
    jwt:
      secret: 123456
      expiration: 36000
  doc:
    gateway:
      enable: true
      resources: "FEBS-Server-System,FEBS-Server-Test,FEBS-Auth,FEBS-Server-Generator,FEBS-Server-Job"

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
    socialfallback:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000    

ribbon:
  eager-load:
    enabled: true

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: health,info,gateway
```
注意   uri: lb:ws://FEBS-Server-System
#### 网关过滤器解决跨域
```Java
import org.springframework.core.Ordered;
import org.springframework.core.annotation.Order;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.server.reactive.ServerHttpRequest;
import org.springframework.http.server.reactive.ServerHttpResponse;
import org.springframework.stereotype.Component;
import org.springframework.web.cors.reactive.CorsUtils;
import org.springframework.web.server.ServerWebExchange;
import org.springframework.web.server.WebFilter;
import org.springframework.web.server.WebFilterChain;
import reactor.core.publisher.Mono;

@Component
@Order(Ordered.HIGHEST_PRECEDENCE)
public class WebFluxSecurityCorsFilter implements WebFilter {

    @Override
    @SuppressWarnings("all")
    public Mono<Void> filter(ServerWebExchange exchange, WebFilterChain chain) {
        ServerHttpRequest request = exchange.getRequest();
        if (CorsUtils.isCorsRequest(request)) {
            String origin =request.getHeaders().getOrigin();
            ServerHttpResponse response = exchange.getResponse();
            HttpHeaders headers = response.getHeaders();
            headers.add("Access-Control-Allow-Origin", origin);
            headers.add("Access-Control-Allow-Methods", "*");
            headers.add("Access-Control-Max-Age", "3600");
            headers.add("Access-Control-Allow-Headers", "*");
            if (request.getMethod() == HttpMethod.OPTIONS) {
                response.setStatusCode(HttpStatus.OK);
                return Mono.empty();
            }
        }
        return chain.filter(exchange);
    }
}
```
Access-Control-Allow-Origin的值设置为请求Header中的域名不能为‘*’
#### 网关过滤器解决跨域响应多个origin信息
前端会发起一个  /my-chat-app/info 请求，my-chat-app为 websocket 的 Endpoint
```Java
import cc.mrbird.febs.common.core.entity.constant.FebsConstant;
import cc.mrbird.febs.gateway.enhance.service.RouteEnhanceService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.cloud.gateway.filter.GatewayFilterChain;
import org.springframework.cloud.gateway.filter.GlobalFilter;
import org.springframework.core.Ordered;
import org.springframework.http.HttpHeaders;
import org.springframework.http.server.reactive.ServerHttpRequest;
import org.springframework.stereotype.Component;
import org.springframework.util.AntPathMatcher;
import org.springframework.util.Base64Utils;
import org.springframework.web.server.ServerWebExchange;
import org.springframework.web.util.UriComponentsBuilder;
import reactor.core.publisher.Mono;
import java.net.URI;
import java.util.ArrayList;

import static org.springframework.cloud.gateway.support.ServerWebExchangeUtils.GATEWAY_REQUEST_URL_ATTR;

@Slf4j
@Component
@RequiredArgsConstructor
public class FebsGatewayRequestFilter implements GlobalFilter,Ordered {

    private final RouteEnhanceService routeEnhanceService;
    private final AntPathMatcher pathMatcher = new AntPathMatcher();
    @Value("${febs.gateway.enhance:false}")
    private Boolean routeEhance;
    private final static String DEFAULT_FILTER_PATH = "/my-chat-app/info";
    @Override
    public Mono<Void> filter(ServerWebExchange exchange, GatewayFilterChain chain) {
        URI requestUrl = exchange.getRequiredAttribute(GATEWAY_REQUEST_URL_ATTR);
        String scheme = requestUrl.getScheme();
        if (DEFAULT_FILTER_PATH.equalsIgnoreCase(requestUrl.getPath())) {
      // ws请求转换为 http请求
            String wsScheme = convertWsToHttp(scheme);
            URI wsRequestUrl = UriComponentsBuilder.fromUri(requestUrl).scheme(wsScheme).build().toUri();
            exchange.getAttributes().put(GATEWAY_REQUEST_URL_ATTR, wsRequestUrl);
        }
        if (routeEhance) {
            Mono<Void> blackListResult = routeEnhanceService.filterBlackList(exchange);
            if (blackListResult != null) {
                routeEnhanceService.saveBlockLogs(exchange);
                return blackListResult;
            }
            Mono<Void> rateLimitResult = routeEnhanceService.filterRateLimit(exchange);
            if (rateLimitResult != null) {
                routeEnhanceService.saveRateLimitLogs(exchange);
                return rateLimitResult;
            }
            routeEnhanceService.saveRequestLogs(exchange);
        }

        byte[] token = Base64Utils.encode((FebsConstant.GATEWAY_TOKEN_VALUE).getBytes());
        String[] headerValues = {new String(token)};
        ServerHttpRequest build = exchange.getRequest().mutate().header(FebsConstant.GATEWAY_TOKEN_HEADER, headerValues).build();
        ServerWebExchange newExchange = exchange.mutate().request(build).build();

        //解决返回多个origin信息
        return chain.filter(newExchange).then(Mono.defer(() -> {
            newExchange.getResponse().getHeaders().entrySet().stream()
                    .filter(kv -> (kv.getValue() != null && kv.getValue().size() > 1))
                    .filter(kv -> (kv.getKey().equals(HttpHeaders.ACCESS_CONTROL_ALLOW_ORIGIN)
                            || kv.getKey().equals(HttpHeaders.ACCESS_CONTROL_ALLOW_CREDENTIALS)))
                    .forEach(kv ->
                    {
                        kv.setValue(new ArrayList<String>() {{
                            add(kv.getValue().get(0));
                        }});
                    });

            return chain.filter(newExchange);
        }));
    }

    @Override
    public int getOrder() {
       return Ordered.LOWEST_PRECEDENCE - 2;
    }

    static String convertWsToHttp(String scheme) {
        scheme = scheme.toLowerCase();
        return "ws".equals(scheme) ? "http" : "wss".equals(scheme) ? "https" : scheme;
    }
}
```
#### websocket配置
```Java
import org.springframework.context.annotation.Configuration;
import org.springframework.messaging.simp.config.MessageBrokerRegistry;
import org.springframework.web.socket.config.annotation.EnableWebSocketMessageBroker;
import org.springframework.web.socket.config.annotation.StompEndpointRegistry;
import org.springframework.web.socket.config.annotation.WebSocketMessageBrokerConfigurer;

@Configuration
@EnableWebSocketMessageBroker
public class WebSocketConfig implements WebSocketMessageBrokerConfigurer {

    @Override
    public void registerStompEndpoints(StompEndpointRegistry registry) {
        registry
                .addEndpoint("/my-chat-app")
               .setAllowedOrigins("*")
                .withSockJS();
    }

    @Override
    public void configureMessageBroker(MessageBrokerRegistry registry) {
        registry.setApplicationDestinationPrefixes("/app");
        registry.enableSimpleBroker("/topic");
    }
}
```
#### websocket订阅
```Java
@Slf4j
@RestController
public class ChatController {
    @Autowired
    IChatRoomService chatRoomService;

    @MessageMapping("/chat.send")
    @SendTo("/topic/public")
    public Message sendMessage(@Payload Message message) {
        return chatRoomService.retrieveMessageToSend(message);
    }

    @MessageMapping("/chat.register")
    @SendTo("/topic/public")
    public Message register(@Payload Message message, SimpMessageHeaderAccessor headerAccessor) {
        headerAccessor.getSessionAttributes().put("username", message.getSender());
        headerAccessor.getSessionAttributes().put("userAvatarImage", message.getAvatarImage());
        return chatRoomService.retrieveUserConnectionStatus(message, message.getActionType());
    }



    @GetMapping("messages")
    public FebsResponse chatRoomList(QueryRequest request, Message chatRoom) {
        IPage<Message> page = this.chatRoomService.findChatRooms(request, chatRoom);
        return new FebsResponse().status(HttpStatus.OK.value()).data(page);
    }
}
```
#### Vue前端依赖
```
"sockjs-client": "^1.5.0",
"webstomp-client": "^1.2.6"
```
#### Vue页面
```
<template>
  <div class="chat-room-container col-md-12 col-sm-12 col-xs-12">

    <ChatRoomView :received-messages="receivedMessages" />

    <SendMessageView
      :has-max-length="hasMaxLength"
      @send-message="sendMessage"
      @is-valid-input-string="isHasMaxLength"
      @update-message-to-send="updateMessageToSend"
    />

  </div>
</template>

<script>
import ChatRoomView from './ChatRoomView'
import SendMessageView from './SendMessageView'
import axios from 'axios'
import SockJS from 'sockjs-client'
import Stomp from 'webstomp-client'
import { getToken } from '@/utils/auth'
export default {
  name: 'ChatRoomComponent',
  components: {
    ChatRoomView,
    SendMessageView
  },
  data() {
    return {
      connected: false,
      hasMaxLength: false,
      maxMessageLength: 150,
      receivedMessages: []
    }
  },
  mounted() {
    this.connect()
  },
  updated() {
    const container = this.$el.querySelector('#container')
    container.scrollTop = container.scrollHeight
  },
  methods: {
    connect() {
      const url = 'http://192.168.0.110:8301/system/my-chat-app?access_token=' + `${getToken()}`
      // const url = 'http://192.168.0.110:8301/system/my-chat-app'
      this.socket = new SockJS(url)
      // this.socket.withCredentials = true
      this.stompClient = Stomp.over(this.socket)

      this.stompClient.connect(
        { },
        frame => {
          this.connected = true

          this.stompClient.subscribe('/topic/public', tick => {
            const messageResponse = JSON.parse(tick.body)

            const message = {
              message: messageResponse.message,
              messageDate: messageResponse.timeStamp,
              messageType: messageResponse.actionType,
              messageSender: messageResponse.sender,
              messageAvatar: messageResponse.avatarImage

            }

            if (message.messageType === 'JOIN') {
              this.retrieveMessageHistory()
            }
            this.receivedMessages.push(message)
          })

          this.sendJoinedMessage()
        }, error => {
          console.log('error')
          console.log(error)

          this.connected = false
        }
      )
    },
    sendJoinedMessage() {
      const userJoined = {
        sender: this.$store.state.account.user.username,
        actionType: 'JOIN',
        avatarImage: this.$store.state.account.user.avatar
      }

      this.stompClient.send('/app/chat.register', JSON.stringify(userJoined), {})
    },
    sendMessage() {
      const messageToSend = this.$store.state.websocket.messageToSend
      if (!this.hasMaxLength && messageToSend !== '') {
        if (this.stompClient && this.stompClient.connected) {
          const chatPayload = {
            sender: this.$store.state.account.user.username,
            message: messageToSend,
            actionType: 'CHAT',
            avatarImage: this.$store.state.account.user.avatar
          }

          this.stompClient.send('/app/chat.send', JSON.stringify(chatPayload))
          this.$store.commit('websocket/setMessageToSend', '')
        }
      }
    },
    retrieveMessageHistory() {
      const url = 'http://192.168.0.110:8301/system/messages?access_token=' + `${getToken()}`
      return axios.get(url)
        .then(response => response.data)
        .then(data => {
          const messages = []
          data.data.records.map(message => {
            const log = {
              message: message.message,
              messageDate: message.timeStamp,
              messageType: message.actionType,
              messageSender: message.sender,
              messageAvatar: message.avatarImage
            }

            messages.push(log)
            this.receivedMessages = messages
          })
        })
    },
    updateMessageToSend(e) {
      this.$store.commit('websocket/setMessageToSend', e)
      this.isHasMaxLength()
    },
    isHasMaxLength() {
      this.hasMaxLength = this.$store.state.websocket.messageToSend.length >= this.maxMessageLength
    }
  }
}
</script>

<style scoped>
  .chat-room-container {
    color: white;
    height: 90vh;
    margin-top: 5%;
    color: black;
  }

</style>

```
#### 相关组件
SendMessageView.vue
```
<template>
  <div class="send-message-container col-md-12 col-sm-12 col-xs-12 container-fluid">
    <div class="">

      <div class="row">
        <span v-if="hasMaxLength" class="input-error-message-container">
          <div class="input-error-message">
            Max number of charters is 150
          </div>
        </span>
      </div>

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="message-input-container">
          <input
            placeholder="type message"
            class="send-message-input"
            :class="{'input-error': hasMaxLength}"
            :value="this.$store.state.websocket.messageToSend"
            @input="$emit('update-message-to-send', $event.target.value)"
            @keyup.enter="$emit('send-message')"
          >
        </div>

      </div>

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="message-button-container">
          <button
            class="send-button"
            @click="$emit('send-message')"
          >
            Send Message
          </button>
        </div>
      </div>

    </div>
  </div>
</template>

<script>

export default {
  name: 'SendMessageView',
  components: {},
  props: {
    hasMaxLength: {
      type: Boolean
    }
  }
}

</script>

<style scoped>
    .send-message-container {
        background: black;
        height: 25vh;
        text-align: center;
    }

    .input-error-message-container{
        border-color: red;
        border-width: 1px;
        background: hsla(0, 65%, 75%, 1);
        width: 30%;
        height: 5vh;
        transition: all;
    }
    .input-error-message {
        color: red;
        display: block;
        font-size: 15px;

    }
    .input-error{
        border-color: red;
        border-width: 1px;
        background: hsla(0, 65%, 75%, 1);
    }

    .message-input-container {
        margin-top: 2%;
    }
    .send-message-input {
        width: 64%;
        padding: 1%;
    }

    .message-button-container {
        margin-top: 2%;
    }
    .send-button {
        height: 5vh;
        width: 30%;
        font-size: 17px;
    }

    @media screen and (max-width: 550px){
        .message-input-container {
            margin-top: 5%;
        }
        .send-message-input {
            width: 100%;
            padding: 1%
        }
        .message-button-container {
            margin-top: 5%;
        }
        .send-button {
            height: 5vh;
            width: 60%;
            font-size: 17px;
        }
    }

    @media screen and (max-width: 450px) {
        .message-input-container {
            margin-top: 12%;
        }

        .send-button {
            height: 5vh;
            width: 70%;
            font-size: 17px;
        }
    }
</style>
```
ChatRoomView.vue
```
<template>
  <div class="chat-container col-md-12 col-sm-12 col-xs-12">
    <div class=" row message-topic-header">
      Welcome to the Chat Room
    </div>

    <vue-custom-scrollbar id="container" class="scroll-area">
      <div id="messagesContainer" class="row messages-container nopadding col-md-12 col-sm-12 col-xs-12">

        <div v-for="message in receivedMessages" :key="message.date" class="message-container col-md-12 col-sm-12 col-xs-12" :class="{'message-container-join': message.messageType === 'JOIN'}">

          <div class="message" :class="{'message-join': ( message.messageType === 'JOIN' || message.messageType === 'LEAVE' ) }">
            <span class="message-avatar text-xs-left col-md-1 col-sm-2 col-xs-4" :class="{'message-avatar-joined': ( message.messageType === 'JOIN' || message.messageType === 'LEAVE' ) }">
              <img :src="resoleveMessageAvatar(message.messageAvatar)" alt="message.messageAvatar" class="avatar-image ">
            </span>
            <span :class="( message.messageType === 'JOIN' || message.messageType === 'LEAVE' ) ? 'message-text-joined col-md-12 col-sm-12 col-xs-12' : 'message-text col-md-9 col-sm-8 col-xs-8'">
              <span :class="( message.messageType === 'JOIN' || message.messageType === 'LEAVE' ) ? 'message-user-name-joined' : 'message-user-name' ">
                &#60;{{ message.messageSender }}&#62;
              </span>
              {{ message.message }}
            </span>
            <span class="message-date text-right col-md-2 col-sm-2 col-xs-12" :class="{'message-date-joined': ( message.messageType === 'JOIN' || message.messageType === 'LEAVE' ) }">
              {{ message.messageDate }}
            </span>
          </div>

        </div>

      </div>
    </vue-custom-scrollbar>
  </div>
</template>

<script>
import VueCustomScrollbar from 'vue-custom-scrollbar/src/vue-scrollbar'

export default {
  name: 'ChatRoomView',
  components: { VueCustomScrollbar },
  props: {
    receivedMessages: {
      type: Array,
      default: () => []
    }
  },
  methods: {
    resoleveMessageAvatar(avatar) {
      return require(`@/assets/avatar/${avatar}`)
    }
  }
}
</script>

<style scoped>
    .message-topic-header {
        color: white;
        background: black;
    }

    .chat-container {
        height: 60vh;
        background: #283248;
    }

    .messages-container {
        margin-top: 3%;
        margin-left: 0% !important;
        margin-bottom: 3%;
    }
    .scroll-area {
        position: relative;
        margin: auto;
        width: 100%;
        height: 100%;
    }
    .message-container {
        height: 7vh;
        width: 100%;
        color: black;
    }
    .message-container-join {
        height: 3vh;
    }
    div.message-container:nth-of-type(even) {
        background: #18294A  !important;
        height: 100%;
    }
    div.message-container:nth-of-type(odd) {
        height: 100%;
    }

    .message {
        text-align: left;
    }
    .message-join{
        text-align: center !important;
    }
    .message-avatar-joined {
        display: none !important;
        color: white;
    }
    .message-user-name-joined {
        display: none !important;
    }
    .message-date-joined {
        display: none !important;
        color: white;
    }
    .message-text-joined {
        color: lime !important;
    }
    .message-user-name {
        color: lime;
    }

    .message-avatar {
        color: black;
    }
    .avatar-image {
        width: 70%;
        padding: 5px;
        height: 5vh;
    }
    @media screen and (min-width: 995px) and (max-width: 1150px){
        .avatar-image {
            width: 100%;
            padding: 5px;
            height: 5vh;
        }
    }
    @media screen and (max-width: 765px){
        .avatar-image {
            width: 50%;
            padding: 5px;
            height: 5vh;
        }
    }
    @media screen and (max-width: 500px){
        .avatar-image {
            width: 100%;
            padding: 5px;
            height: 5vh;
        }
    }

    .message-text {
        color: white;
        overflow-wrap: break-word;
        display: block;
    }
    .message-date {
        font-size: 12px;
        color: lightgray;
        float: right;
        margin-top: 1%;
    }
</style>
```
界面预览
![image](https://user-images.githubusercontent.com/19374409/103202808-5f3ba600-492e-11eb-8eab-0abf03156281.png)
