### ISSUE TITLE
Docker环境下MinIo从单体迁移至分布式部署攻略

### ISSUE THREAD

**Issue by RandolphChin** [RandolphChin/RandolphChin.github.io#324]
参考自[ 梦想实现家_Z](https://juejin.cn/post/7128064094061461534) 和 [百里登峰](https://www.cnblogs.com/braveym/p/15633596.html)

需求：原来 MinIO是单体部署，在31服务器，升级为分布式部署，两台内网服务器31和33，每台服务器两个节点(内网无法访问外网)

#### 1 下载 docker-compose ，离线服务器只能下载后安装(可连接外网忽略)
download from [github](https://github.com/docker/compose/releases) https://github.com/docker/compose/releases
选择  docker-compose-linux-x86_64 ，最新版可以要选择编译平台，选择次新版本有 x86-64 这一下载项
#### 2 下载 minio client客户端(可连接外网忽略)
有外网环境下
```
docker run -it --entrypoint=/bin/sh minio/mc     
```
无外网下，可先行在有外网电脑上安装 mc,再导出 tar 包，最后再导入服务器即可

1 存出镜像(如果 TAG 是 latest 则不用填写TAG内容)
```
    docker save -o FILE_NAME.tar IMAGE_NAME:TAG
```
2 载入镜像
```
    docker load -i FILE-NAME.tar
    or
    docker load < FILE-NAME.tar
```
#### 6 安装 docker-compose
```
mv  docker-compose-linux-x86_64  /usr/local/bin/
//修改文件名
 mv docker-compose-linux-x86_64 docker-compose
//授权
sudo chmod +x /usr/local/bin/docker-compose
//查看安装是否成功
docker-compose -v
```
#### 7 删除 31服务器上的 minio容器(端口重了，再更改一个端口)
```
docker   stop  minio
docker  rm  minio
```
#### 8 在31 服务器和 33服务器分别启动 minio
进入 docker-compose.yml 所在的目录，执行  docker-compose  up 即可
#### 9 在31服务器启动旧版 minio 端口不再是 9000，指定为 9999
目的是分布式的minio，从单体中同步历史数据
```
docker run -p 9090:9090 -p 9999:9999 --name minio -e MINIO_ACCESS_KEY=YOUR_Account -e MINIO_SECRET_KEY=YOUR_Pwd -e "TZ=Asia/Shanghai"  -v /home/dockerFile/minio/data:/data  minio/minio:latest server --console-address ":9090" --address ":9999" /data
```
#### 10 在33服务器导入 mc.tar 
```
docker  load -i  mc.tar
```
#### 11 运行 minio client 容器 mc
```
docker run -it --entrypoint=/bin/sh minio/mc
```
#### 12 运行 mc命令，31文件复制至 33
```
mc config host add minio_31  http://192.168.2.31:9999  YOUR_Account Your_pwd

mc config host add minio_33  http://192.168.2.33:9000  YOUR_Account YOUR_pwd

//test connection
mc admin info minio_31
mc mirror --remove --overwrite --watch  minio_31  minio_33
```
#### 13 更改 33 服务器上minio文件夹权限 private 为 public,更改33会自动更改31

docker-compose.yml文件如下
```
version: '3.7'
services:
  minio:
    image: 'minio/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - '/home/dockerFile/minio/data:/data1'
      - '/home/dockerFile/minio/data2:/data2'
    command: >-
      server --console-address ":9001" http://192.168.2.31:9000/data{1...2}
      http://192.168.2.33:9000/data{1...2}
    environment:
      - MINIO_ROOT_USER=YOUR_Account
      - MINIO_ROOT_PASSWORD=YOUR_pwd
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:9000/minio/health/live'
      interval: 30s
      timeout: 20s
      retries: 3
    network_mode: host
    restart: always
```
nginx中关于 minio的配置如下 minio.conf 入在 nginx 目录的 conf.d 目录内
```
upstream minio {
    server 192.168.2.31:9000;
    server 192.168.2.33:9000;
}

upstream console {
    ip_hash;
    server 192.168.2.31:9001;
    server 192.168.2.33:9001;
}

server {
    listen       9000;
    listen  [::]:9000;
    server_name  127.0.0.1;

    # To allow special characters in headers
    ignore_invalid_headers off;
    # Allow any size file to be uploaded.
    # Set to a value such as 1000m; to restrict file size to a specific value
    client_max_body_size 0;
    # To disable buffering
    proxy_buffering off;
    proxy_request_buffering off;

    location / {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 300;
        # Default is HTTP/1, keepalive is only enabled in HTTP/1.1
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        chunked_transfer_encoding off;

        proxy_pass http://minio;
    }
}

server {
    listen       9001;
    listen  [::]:9001;
    server_name  localhost;

    # To allow special characters in headers
    ignore_invalid_headers off;
    # Allow any size file to be uploaded.
    # Set to a value such as 1000m; to restrict file size to a specific value
    client_max_body_size 0;
    # To disable buffering
    proxy_buffering off;
    proxy_request_buffering off;

    location / {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-NginX-Proxy true;

        # This is necessary to pass the correct IP to be hashed
        real_ip_header X-Real-IP;

        proxy_connect_timeout 300;
        
        # To support websocket
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        
        chunked_transfer_encoding off;

        proxy_pass http://console;
    }
}
```
